# site settings
title: Vedrana Vidulin
brief-intro: "Data scientist and bioinformatician"
baseurl: "" # the subpath of the site, e.g. /blog
url: "http://vedranavidulin.com" # the base hostname & protocol for the site

permalink: /:year/:month/:day/:title/

# profiles
twitter_username: Vedrana_Vidulin
facebook_username: vedrana.vidulin
github_username:  vedranav
linkedIn_username: vedrana-vidulin

description_footer: <i class="fa fa-copyright" aria-hidden="true"></i> 2020 by Vedrana Vidulin

# statistic analysis
google_analytics_id: UA-98660811-1

# pageclip contact form id
pageclip_contact_form_id: mFeqfBadhhDUeokfFwQMF07dtnManvuv/contact-form

# build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
plugins: [jekyll-paginate]
paginate: 6
